// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "ap-southeast-2",
    "aws_cognito_identity_pool_id": "ap-southeast-2:922dcc05-68b9-4c72-ad3f-fa6ee837d882",
    "aws_cognito_region": "ap-southeast-2",
    "aws_user_pools_id": "ap-southeast-2_k0ytsSMKu",
    "aws_user_pools_web_client_id": "7i669s31bti5t4a3808dlt3qm0"
};


export default awsmobile;
